language: android
android:
  components:
    - build-tools-22.0.0
		- android-22
		- android-21
    - android-19
    - android-7
    - android-14
    - android-16
		- extra-android-support
		- extra-google-m2repository
		- extra-android-m2repository
  licenses:
    - 'android\-sdk\-license\-.*'
