language: android
android:
  components:
    - android-19
    - android-7
    - android-14
    - android-16
script:
  - cd application
  - android update project -p . --name Atomic --subprojects --target android-19
  - ant clean debug
